name: english
description: Helper for keeping English-Russian dictionary in Obsidian.
version: 0.0.1
repository: https://github.com/Lynx20wz/dart_english
publish_to: none

environment:
  sdk: ^3.10.4

workspace:
  - packages/english_core
  - packages/english_cli
  - packages/english_flutter

dev_dependencies:
  lints: ^6.0.0
