name: english_core
description: Core library for English-Russian dictionary.
version: 0.0.1
repository: https://github.com/Lynx20wz/dart_english

resolution: workspace

environment:
  sdk: ^3.10.4
dependencies:
  dotenv: ^4.2.0
  html: ^0.15.6
  http: ^1.6.0
  path: ^1.9.1
  yandex_dictionary_api: ^1.0.1
dev_dependencies:
  test: ^1.26.3
