name: english_cli
description: Command-line interface for English dictionary.
version: 0.0.1
homepage: https://github.com/andrew-belyaev/english_cli
publish_to: none

resolution: workspace

environment:
  sdk: ^3.10.4
dependencies:
  args: ^2.7.0
  path: ^1.9.1
  english_core:
    path: ../english_core
